name: stock_manager
description: "Your App to control your Stock"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  barcode_scan2: ^4.3.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
